name: tws

services:
  postgres:
    restart: unless-stopped
    container_name: db
    image: mirror.gcr.io/postgres:latest
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "shared_buffers=1GB"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_DB=db
    volumes:
      - database:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  server:
    restart: unless-stopped
    container_name: server
    image: mirror.gcr.io/bitnami/wildfly:latest
    environment:
      - WILDFLY_USERNAME=${WILDFLY_USERNAME:-admin}
      - WILDFLY_PASSWORD=${WILDFLY_PASSWORD:-adminadmin123}
      - WILDFLY_MANAGEMENT_LISTEN_ADDRESS=0.0.0.0
      - JBOSS_BIND_ADDRESS=0.0.0.0
    ports:
      - "8080:8080"
      - "9990:9990"
  
  juddi:
    restart: unless-stopped
    container_name: juddi
    build:
      context: .
      dockerfile: juddi.Dockerfile
      args:
        - USERNAME=${JUDDI_USER:-juddi}
        - PASSWORD=${JUDDI_PASSWORD:-admin}
    ports:
      - "8999:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  database:
