package ksrve.proxy.model.entity;

import ksrve.proxy.model.dto.EmployeeDTO;
import lombok.*;

import java.util.Date;

/**
 * Entity class representing an Employee in the system.
 * <p>
 * This class is mapped to the "employee" table in the database and
 * contains fields related to employee details such as first name,
 * last name, email, department, and hire date.
 * </p>
 */
@ToString
@RequiredArgsConstructor
@AllArgsConstructor
@Builder
@Getter
@Setter
public class Employee {

    /**
     * Unique identifier for the Employee.
     * This is the primary key for the employee entity,
     * which is automatically generated by the database.
     */
    private Integer id;

    /**
     * First name of the Employee.
     * This field stores the employee's first name.
     */
    private String firstName;

    /**
     * Last name of the Employee.
     * This field stores the employee's last name.
     */
    private String lastName;

    /**
     * Email address of the Employee.
     * This field stores the employee's email address.
     */
    private String email;

    /**
     * Department in which the Employee works.
     * This field represents the department associated with the employee.
     */
    private String department;

    /**
     * Date the Employee was hired.
     * This field indicates when the employee was hired, stored as a Date object.
     */
    private Date hireDate;

    /**
     * Maps this Employee entity to an EmployeeDTO.
     * <p>
     * This method allows conversion from the Entity representation
     * to a Data Transfer Object, making it easy to transmit
     * relevant employee information within the application layer.
     * </p>
     *
     * @return an EmployeeDTO object containing employee details.
     */
    public EmployeeDTO mapToDTO() {
        return new EmployeeDTO(this);
    }
}